WIP: Interruption investigation
Effect-TS/core pull request #871
Opened 2021-09-24 05:22 UTC by r-cyr

2021-09-28 06:02 UTC, mikearnaldi commented
Reverting the changes to workaround interruption it seems the skipped test now throws an exception somewhere.

![Screenshot 2021-09-28 065925](https://user-images.githubusercontent.com/24249610/135031811-8f893800-ac47-49a1-ad33-01d2b984b4e8.png)

2021-09-28 06:09 UTC, mikearnaldi requested changes

2021-09-28 06:09 UTC, mikearnaldi commented on packages/system/src/Stream/Stream/effectAsyncInterrupt.ts
> +                if (e instanceof CS.FiberFailure) {
better to avoid instanceof comparism

2021-09-28 06:09 UTC, mikearnaldi commented on packages/system/src/Stream/Stream/effectAsyncInterrupt.ts
> +                if (e instanceof CS.FiberFailure) {
also is there a specific reason to use a promise? runPromise hides the full cause

2021-09-28 06:29 UTC, mikearnaldi commented on packages/system/src/Effect/effectAsyncInterrupt.ts
> +  register: (cb: Cb<Effect<R, E, A>>) => E.Either<Canceler<R>, Effect<R, E, A>>,
didn't we have the *Maybe variants that returned an either?

2021-09-29 02:24 UTC, r-cyr commented
Removed Stream effectAsync implementations

2021-09-29 08:55 UTC, merged